### ISSUE TITLE
Make sure system works on Mainnet

### ISSUE THREAD

**Issue by volovyks** [near/mpc#574]
### Description
Latencies on Mainnet, especially lake framework latencies, can be different from Testnet. Let's make sure our system is operational before the Mainnet release.

**Comment by kmaus-near** [comment]
@volovyks or @ppca do we have a tfvars file we want to use for this? Once I have that I can  deploy the 8 nodes as discussed on mainnet.

**Comment by kmaus-near** [comment]
Still need to sync with @ppca for a mainnet contract.

**Comment by volovyks** [comment]
@kmaus-near @ppca why is this blocked?

**Comment by ppca** [comment]
We've got mainnet dev on. The contract is `multichain-mpc-dev.near`.
Have sent sign tx and succeeded. We are putting up a dashboard for mainnet dev and also will load test a bit.

**Comment by volovyks** [comment]
Cool! Thank you.

**Comment by kmaus-near** [comment]
Currently in progress still.
