### ISSUE TITLE
modify contract with yield/resume

### ISSUE THREAD

**Issue by ppca** [near/mpc#593]
now that yield/resume is on testnet, we should modify our contract and test it out on dev.

**Comment by ChaoticTempest** [comment]
There's no clear timeline on when it will make it to mainnet, so we might want to punt this until there's a clear timeline. That way we don't have this on testnet but have to wait for it to be on mainnet to actually go mainnet on our MPC network

**Comment by volovyks** [comment]
We should keep the old recursive design and add a new yield function to stay flexible with our release date.
Currently, this issue is blocked by Near SDK updates.

**Comment by volovyks** [comment]
NEAR SDK updates were merged. We can start working on this.
Saving a recursive design is unnecessary if the new yield/resume is stable.
