### ISSUE TITLE
Deploy and Update instructions

### ISSUE THREAD

**Issue by volovyks** [near/mpc#599]
### Description

All the deployments and update processes must be documented and visible to all team members.
And let's not forget about the least of permissions that are needed to accomplish all the steps.

**Comment by volovyks** [comment]
Here is a draft from @ppca: https://docs.google.com/document/d/1rVWey6kLg-t0zAg_kNyzMin6_v14kEMAXkxRdsan51U/edit

**Comment by mikedotexe** [comment]
> Here is a draft from @ppca: https://docs.google.com/document/d/1rVWey6kLg-t0zAg_kNyzMin6_v14kEMAXkxRdsan51U/edit

Can we make this doc public?

**Comment by volovyks** [comment]
It may not benefit our security as it includes what kind of secrets we need and how we use them.
Our terraform setup is public. We can make more information public since it's an open-source decentralized project. Tell me if you have something specific in mind.

**Comment by kmaus-near** [comment]
Will work on this, I will update the README in the infra directory with our current process.

**Comment by volovyks** [comment]
@kmaus-near let's have a doc with a list of permissions needed to deploy (private).
