### ISSUE TITLE
Setup On-call schedule for Multi-chain MPC

### ISSUE THREAD

**Issue by volovyks** [near/mpc#602]
### Description
Testnet for now, Mainnet once it is released

**Comment by kmaus-near** [comment]
@ppca I'll need your input on this one. I can set the schedule, but we should set up certain metric alerts for the [dashboard](https://nearinc.grafana.net/d/bdg2srektjy0wd/chain-signatures?orgId=1&from=now-12h&to=now) so we have something to push to a rotation. Basically what metrics we should alert on and send to the alert groups, what should their severity be, and what the escalation for those alerts should be.

**Comment by kmaus-near** [comment]
Also @ChaoticTempest please accept grafana invite so I can add you to a schedule.

**Comment by ChaoticTempest** [comment]
@kmaus-near done, but it did come up with an error the first time I pressed the link so let me know if I need to do anythin

**Comment by kmaus-near** [comment]
We have a loose schedule now, I still need to add @ailisp to grafana.

I'm working on separating oncall by timezone, which timezones (preferably static) should I add to the schedule? Clearly US based, mostly just wondering about APAC or EU zones. Hopefully this way there is less chance of someone being oncall outside of working hours.

**Comment by volovyks** [comment]
@kmaus-near , @ailisp already installed the app. Please, contact him in Slack if there are any issues.

**Comment by kmaus-near** [comment]
Everyone on the team will need to go [here](https://nearinc.grafana.net/a/grafana-oncall-app/users?p=1) search for their user, and add a phone number and integrate with the mobile app, please let me know if you can't edit your own users information and I'll give you access to do so.
