### ISSUE TITLE
return root and user pk as a point or string, not near_sdk::PK

### ISSUE THREAD

**Issue by volovyks** [near/mpc#665]

**Comment by ppca** [comment]
@volovyks so in this PR https://github.com/near/mpc/pull/683 @ChaoticTempest  mentioned it is better to use our custom defined type, which is the current form in develop. I'm a bit confused where to proceed next.

**Comment by volovyks** [comment]
We will need to brainstorm on this at a meeting. I want everything to be consistent and in the most user-friendly format.
