### ISSUE TITLE
return derived user PK that was used in signing

### ISSUE THREAD

**Issue by volovyks** [near/mpc#666]

**Comment by ppca** [comment]
Hey @volovyks  I was reading through code, and the derived user pk will be different given different path right? So does this issue aim at returning the user pk along with signature in sign() fn or does it aim it creating a new fn that returns user pk?

**Comment by volovyks** [comment]
@ppca it is impossible to receive the derived key in the view function since there is no "predecessor" in view calls.
We need to add the PK used in the signing to the `sign()` result.

**Comment by ppca** [comment]
> @ppca it is impossible to receive the derived key in the view function since there is no "predecessor" in view calls. We need to add the PK used in the signing to the `sign()` result.

Do we have a desired format of the return type?

**Comment by volovyks** [comment]
No specific opinion here, but let's make sure it is the same as in other places, especially `public_key()` function. @ChaoticTempest was suggesting a design for PK in another issue.

**Comment by volovyks** [comment]
Change of a plan. We can have a separate function that will consume gas. But that is fine, since we will make sign() call more lightweight.
