### ISSUE TITLE
mainnet infra setup

### ISSUE THREAD

**Issue by ppca** [near/mpc#678]
To prepare for mainnet partner launch, we'd need to:
1. let's merge the /infra code we have for mainnet dev
2. PR for the /infra code we will use for production partner mainnet
3. a step by step guide for mainnet partners (we could copy and modify the one for testnet)

**Comment by ppca** [comment]
@kmaus-near Would you mind looking into 1 & 2? And let's include @anshal-savla as reviewer for the PRs too.
I'll look into 3.

**Comment by kmaus-near** [comment]
Can do. How are we handling releases for Mainnet? I remember talking about updates being on the partners themselves instead of the method we use in testnet.

**Comment by ppca** [comment]
> Can do. How are we handling releases for Mainnet? I remember talking about updates being on the partners themselves instead of the method we use in testnet.

Yes. We are not going to have watch towers. The partners will update their nodes themselves. We will provide a public image they could use. If they'd like to build the node themselves, how can they do it? @kmaus-near

**Comment by kmaus-near** [comment]
PR nearly ready for this. I plan on adding a solution for creating secrets in a more repeatable manner, and not exposing them in source control.
