### ISSUE TITLE
Audit

### ISSUE THREAD

**Issue by volovyks** [near/mpc#682]
Medium
- [x] #705
- [x] KS–PCS–F–2 Request Counter Incorrectly Updated
- [x] #693

Low
- [x] #700
- [x] #745
- [x] #746
- [x] #702

Informational
- [x] #756
- [x] #755
- [x] #750
- [x] #743
- [x] #741
- [x] #744
- [x] #740
- [x] #742
- [x] #748
- [x] #749
- [x] #758
- [x] #724
- [x] #723
- [x] #721
- [x] #739
- [x] #720
- [x] #747

**Comment by ppca** [comment]
that request counter issue should be fixed in yield resume PR already.

**Comment by DavidM-D** [comment]
First round of the audit completed
