### ISSUE TITLE
Refund if sign() failed

### ISSUE THREAD

**Issue by volovyks** [near/mpc#708]
We need to refund the user's deposit if the sign() call fails for any reason. But let's ensure it is impossible to drain funds from our contract with bad requests.
Proposed by @gagdiez [here](https://github.com/near/mpc/pull/706#discussion_r1686465787).

**Comment by ailisp** [comment]
There are three cases to consider:
1. when the `sign` call fails (not the cross contract call invoked by `sign`), near will automatically return attached deposit back to the caller: https://docs.near.org/build/smart-contracts/anatomy/environment#attached-deposit
2. when the `sign` call succeed, we should refund the difference, this is the [proposal](https://github.com/near/mpc/pull/706#discussion_r1686465787) by @gagdiez 
3. when the `sign` call success, but the cross contract call invoked by `sign`, i.e., `sign_helper`, `clear_state_on_finish`, `return_signature_on_finish` fails, we should refund the remaining over required_deposit

**Comment by volovyks** [comment]
@ailisp 
1. Ok
2. Agree
3. Why not all? It is not the user's fault that one of our functions failed.

**Comment by volovyks** [comment]
Blocked by https://github.com/near/mpc/issues/767

**Comment by volovyks** [comment]
We will push back with #767 for now.
