### ISSUE TITLE
KS–PCS–O–14 Misleading Function Name

### ISSUE THREAD

**Issue by DavidM-D** [near/mpc#721]
The file http_client.rs contains a function named send_encrypted, which does not perform any encryption logic. The encryption is performed by MessageQueue.send_encrypted, which uses send_encrypted as a subroutine in its logic. The confusing name could cause errors later on during development.

**Comment by DavidM-D** [comment]
Is this true @ChaoticTempest ?

**Comment by ChaoticTempest** [comment]
One does the encryption and the other does not, but the helper function takes a `message: Vec<Ciphered>` which depends on a already encrypted message so this issue is moot either ways

**Comment by DavidM-D** [comment]
Yup, I agree, the types make it impossible to misuse this function.
