### ISSUE TITLE
KS–PCS–O–10 Minor Code Lints

### ISSUE THREAD

**Issue by DavidM-D** [near/mpc#749]
Using cargo clippy only outputs a single warning:

```
warning: the following packages contain code that will be rejected by a future version of Rust: wasmparser v0.78.2
```

However, using cargo dylint, another Rust linting tool, provides more lints that could be used to improve the quality and the robustness of the code. - call to various functions with mutable reference before error returns (multiple instances) - unnamed constant - commented out code

**Comment by DavidM-D** [comment]
I'm OK with the clippy warning, will look into the dylint warnings.

**Comment by ChaoticTempest** [comment]
this lint is coming from workspaces which uses an old `cargo-near` dependency that hasn't been updated yet with the latest near dependencies. It's a non-issue since this is for testing only

**Comment by DavidM-D** [comment]
The dylint warning look to be more code quality that anything that could actively ruin our day.
