### ISSUE TITLE
Test all contract APIs (Unit tests)

### ISSUE THREAD

**Issue by volovyks** [near/mpc#764]

**Comment by ailisp** [comment]
init, sign, respond and vote to update part of APIs are tested. The missing part is join and vote_ join/reshared/leave/pk.

**Comment by volovyks** [comment]
@ailisp I would prioritize user-facing functions. Voting and resharing are important too.
```rust
fn sign() // tested
fn public_key()
fn derived_public_key()
fn latest_key_version()
fn experimantal_signature_deposit()
```
