### ISSUE TITLE
Nodes are not getting new blocks

### ISSUE THREAD

**Issue by volovyks** [near/mpc#783]
The reason is unknown, it happens regularly. We need better logging. @ChaoticTempest not sure if your last PR is targeting this issue.

**Comment by volovyks** [comment]
Update:
Lake was having trouble recently, but MPC has not started getting new blocks even after it was fixed.
The system was recovered with reboot.

**Comment by ChaoticTempest** [comment]
hmm, did this occur recently? Nodes should not need a reboot as the indexer should retry after stalling for a certain amount of time

**Comment by volovyks** [comment]
yes, this week

**Comment by ppca** [comment]
This might be related to https://github.com/near/mpc/pull/792 not included in rc3.

**Comment by ppca** [comment]
I'm trying to see if I can add an integration test where I mock stuck indexer by disabling the lake proxy then enabling it again. Will update

**Comment by ppca** [comment]
I realized this likely will be able to mock the situation where lake is not getting new blocks, and test whether the indexer is able to catch up by itself after lake recovers. 
But this cannot mock the situation where the indexer itself is stuck. 
So this test will best case ensure that the indexer is able to catch up if it is not stuck itself.

**Comment by volovyks** [comment]
This issue may be outdated.  Let's close in 2 weeks if it is not happening again.
