### ISSUE TITLE
Refund deposit for signature request if deposit is not enough

### ISSUE THREAD

**Issue by think-in-universe** [near/mpc#814]
### Description

When sending a signature request, now dynamic NEAR deposit is required when calling the `sign` function. The required deposit amount is calculated as below. https://github.com/near/mpc/blob/568fb115e2fcdc087f430c64b50f3ebffa92a3fd/chain-signatures/contract/src/lib.rs#L220-L233

While it makes sense to implement kind of congestion control for the MPC network, the current design makes it extremely hard to call the `sign` function from a smart contract that relies on Chain Signature: 
1. The required deposit amount is quite volatile and is hard to get a predictable value especially considering asynchronous nature of cross-contract call on NEAR.
2. The required deposit will be as high as 0.5 NEAR when there're 13 pending requests, which is around $2 when NEAR is at $4. The cost is indeed too high for most protocols built with Chain Signature. If no refund is implemented for signature request, the loss of the contract that calls the `sign` function will grow really quickly. 

For the above reason, we suggest that the `sign` function should return the deposited NEAR if doesn't meet the requirement.

**Comment by ailisp** [comment]
Hi Robert, thanks for your analysis! Sign refund is implemented in #781 and tested in local integration test, but latest production contract is deployed before this PR. We'll see whether we can release a new contract

**Comment by ailisp** [comment]
The contract version with refund is deployed. It refund all deposit when fail and more than required when success. Example: https://nearblocks.io/txns/5s8u43vXGNFobogHVnPZG33SAFPNJqMLHpM3ykeScYAn#tree

**Comment by think-in-universe** [comment]
@ailisp awesome. thanks Bo!
