### ISSUE TITLE
Use Logging scopes in all ower the codebase

### ISSUE THREAD

**Issue by volovyks** [near/mpc#823]
We should have the ability to filter logs by scopes. Now all relevant logs can be lost. For example, when you want to see what is going on in signature or triple generation protocol, but all you see is state updates.

**Comment by ailisp** [comment]
The other problem is the scope of logs are not all correct, some are too detailed than required and some are opposite

**Comment by ppca** [comment]
I looked into this. in gcp logs, you could filter json.target, and it can show up on the left pane like this.
<img width="284" alt="Screenshot 2024-09-23 at 11 27 08 AM" src="https://github.com/user-attachments/assets/2a187981-ee6b-43a0-ae66-1829e5f12aa1">
What you do to achieve this is:
step1. click on any logging message like this one
<img width="868" alt="Screenshot 2024-09-23 at 11 28 10 AM" src="https://github.com/user-attachments/assets/932c95d4-2786-4c5f-ac32-92d2de63e00b">
step2. click on "mpc_node::http_client" in target field in json, and select "add field to log fields pane"
<img width="334" alt="Screenshot 2024-09-23 at 11 29 17 AM" src="https://github.com/user-attachments/assets/08c66d4a-861a-44d8-b455-8797d4827167">

Then you should be able to filter based on the target of the log. The target, in the current state of our repo, is basically where in the code the log is emitted from. And you could select from the pane which targets you want to see, I tried a few, they are quite helpful.

Only <10% does not have target value populated. I'll hunt those down.
