### ISSUE TITLE
presignature is missing when all nodes have same presignature count

### ISSUE THREAD

**Issue by ppca** [near/mpc#852]
When a lot of presignatures are being generated, and we want to generate signature at the same time, we always see “presignature is missing”, but all nodes have same number of presignatures

**Comment by volovyks** [comment]
Can it be the reason for https://github.com/near/mpc/issues/851 ?

**Comment by ppca** [comment]
Last time we found out one mainnet node was not able to respond and after we fix it, it was good. This time it happens on testnet

**Comment by ChaoticTempest** [comment]
https://github.com/near/mpc/pull/869 should resolve this as we don't store presignatures currently causing a misalignment in the number of presignatures on nodes when we do a node upgrade
