### ISSUE TITLE
Protocol stuck debug

### ISSUE THREAD

**Issue by ppca** [near/mpc#882]
We saw both on mainnet, testnet and dev that our protocol could be stuck, meaning that we don't see any logic running inside the loop in MpcSignProtocol.run().

This essentially means the nodes will not respond to triple, presig or signature generation at all.

**Comment by ppca** [comment]
I've spent last 3 days digging into mainnet and dev being stuck.
The common thing between them is 1) one node was kinda unavailable; 2) the iter count of the protocol are both stuck.
mainnet iter count:
<img width="1184" alt="Screenshot 2024-10-09 at 7 04 47 PM" src="https://github.com/user-attachments/assets/2105655f-a7c9-45cd-bec2-fcf55f2d2570">

I note down most of the evidence and links in [dev debug doc](https://docs.google.com/document/d/11dYcRWipVRdqKWXANxCrXL33dyclCijiGYUpbGiNwpE/edit) and [mainnet debug doc](https://docs.google.com/document/d/18Qy-fEzPpyFR3x_fAtDXmHg-FS5PcBZk7-tvURw_zRU/edit)

Findings are as follows: 
1) when one node is offline, i.e. /state cannot be reached, then the other nodes will be stuck, or at least progress very very slowly (1 iteration every few minutes as compared to hundreds per min normally), because there are no time out on the call to get /state: https://github.com/near/mpc/blob/02001efa056af9a0ed02b425db91e6d57f746e57/chain-signatures/node/src/mesh/connection.rs#L52. So it can take arbitrarily wrong for this call to return an error. After adding a 2s timeout, problem is solved;
2) when one node's /msg endpoint cannot be reached, like /msg 502 error on aurora mainnet node, then same issue happens: other nodes can take arbitrarily wrong to return error on /msg call. Fix would be to add timeout too.
3) when fetching contract state/config is not successful, all triple/presig/sig logic will be skipped, we are essentially stuck. https://github.com/near/mpc/blob/02001efa056af9a0ed02b425db91e6d57f746e57/chain-signatures/node/src/protocol/mod.rs#L258. This cannot be helped, because we need the most up to date contract state form near rpc calls.

PR here: https://github.com/near/mpc/pull/883/files

I have not figured out:
1) why aurora got into 502 in the first place. We did not have any logs for them at that time, we have fixed that by asking them to adjust their gcp settings. Thanks to @kmaus-near

**Comment by volovyks** [comment]
```This cannot be helped, because we need the most up to date contract state form near rpc calls.```
Is our node reporting itself as "unavailable" when other nodes are trying to ping it?

**Comment by ppca** [comment]
> `This cannot be helped, because we need the most up to date contract state form near rpc calls.` Is our node reporting itself as "unavailable" when other nodes are trying to ping it?

No, I mean each node need to call near rpc to get the latest contract state, and there's no way we don't do that. So if near rpc is somehow not accepting calls to get contract state, then our protocol will be stuck. And since we need that updated contract state, we cannot do anything about this.
